---
title: "Rcpp1x Proposal"
author: "Romain François"
date: "2017-02-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Problem
=======

This is a proposal for a modernized version of the R/C++ bridge based on more modern
approaches. 

Need for R/C++ API
------------------

R is a great and flexible language for statistics and data analysis, but it sometimes lack
performance.
Connecting R with an high performance language such as C++ is a great 
compromise allowing us to keep using R and yet have access to better performance
on critical parts of the code. 

The success of `Rcpp` (Eddelbuettel and François 2011) is a great testimony of the need within the R 
community to have solid foundations to use R together with C++. A significant subset of R packages
use of `Rcpp` to leverage C++ code, and this extends to a large proportion of packages once
recursive reverse dependencies are taken into account. 

Towards more recent C++ standards
---------------------------------

However ubiquitous, the current implementation of `Rcpp` is maintained with emphasis on interface stability 
and backwards compatibility against old versions of C++, namely `C++98`. Before the release of `C++11`, the language had been 
stagnant for a long period of time. Adoption of modern C++ standards (from `C++11`) by compiler providers has 
taken additional time, and availability of these compilers across relevant platforms suitable for R development 
took further time. 

The completed modernization of the `Rtools` (Murdoch, Ligges, Kou, Ushey, Allaire, Adler and Ooms 2016)
suite for windows set an important milestone about 
availability of modern C++ standards. When developing modern R packages using C++ code, we can now 
safely assume C++11. Furthermore, transitioning from C++11 to more recent versions should 
be less of a struggle. There are still some platforms that don't provide native support for modern standards, 
but compilers can generally be installed as opt-in compilers, and I don't think it is a good idea 
to allow our community to be taken hostage in the past. 

Backwards compatibility with C++98 may initially perceived as a good feature, but in effect it is
our belief that it is in fact a curse in disguise. It forces developers of the R/C++ bridge as well 
as developers to dependent packages to maintain code targeting both modern syntax (using features such as lambdas 
and the `auto` keyword) and outdated C++ idioms. In effect, this leads to conditional compiling and 
therefore code bloat. 

We suggest eliminating this issue altogether by rebasing the R/C++ API codebase on more recent 
C++ standards. Initially we are interested in C++11 which is now universally available 
on the platforms of interest for R package development. 

This allows both the API as well as packages using it to take full advantage of modern C++ syntax, 
leading to better code clarity and concision. For example, large parts of the historic `Rcpp` codebase
are written by means of automatically generated R code that adds thousands of lines of C++ code, 
which can be rewritten using variadic templates in much less code.

Runtime dependency
------------------

The current implementation of the R/C++ API is distributed as an R package containing 
both header files for API classes (e.g. `NumericVector`) and a runtime library that is either 
dynamically or statically linked depending on the platform. 

This separation may cause hurdles between the two translation units involved, which makes 
exception propagation more difficult that it could be. 

Furthermore, the bigger problem is with updates of the API and potential binary 
incompatibilities. When developing a package that uses `Rcpp`, several versions of the 
codebase are involved. 
  - The version of `Rcpp` used by the developer of the package
  - The version of `Rcpp` on CRAN, used i.e. to compile binary versions of the package
  - The version of `Rcpp` on the user's machine
  
When these 3 versions are the same, everything works fine. When they start to differ, dealing with  
complicated binary incompatibility problems start to happen. Package developers
have used various degrees of safeguards to limit the issue, for example always depend on the 
latest version of `Rcpp` but this is far from full proof. 

These issues are hard to find and even harder to deal with. The smallest change in the 
API can trigger the problem. The maintainers of `Rcpp` are well aware of it, and have chosen
to deal with it by limiting the number of API changes to a strict minimum, making it
extremely difficult to let the API evolve, and for example come back on some early design 
mistakes. 

Our envisioned solution to work around this issue is twofold:
  - The API will exclusively provide header files. 
  - The API will be distributed in a way that makes it embeddable in the client package. A client 
    package will consist on original code using headers of the API that will be stored somewhere 
    within the package
    
With these two design conditions, the version of the API used for a package is the same across 
all scenarios. The version of the API used on the installed package of some user is the same
as the version of the API used by the cran package, which is also the same as the version of the 
API that has been used to develop the package. 

Ugrading to a newer version of the API becomes the responsibility of the developer of the 
client package. This will dramatically reduce binary incompatibility issues. 

This distribution model gives developers of the R/C++ API much more latitude to make 
potentially breaking changes, eliminate dead code or simply redesign parts of the API
that deserve it. 

Modularity
----------

Currently, when using `Rcpp`, we include all of the code base with `#include <Rcpp.h>`, 
this pulls in all of the code base, including API classes, sugar and modules. However 
sometimes only a limited fraction of the codebase is effectively used. For example
some code might only use numeric vectors. 

We will look at solutions allowing to extract only the relevant part of the API
for the target use. 

Code Complexity
---------------

Some classes in the current implementation of `Rcpp` suffer from the design as you go
pattern and expose an overly complicated API. For example, the vector classes
(e.g. `NumericVector`) have too many constructors. The constructors can advantageously 
be replaced by appropriate free functions. 

Another side effect of the code complexity is compile time. Compiling a package against `Rcpp`
takes too much time. I believe that this time can be dramatically reduced by this approach. 
Furthermore, this approach will also reduce continuous integration time. At the moment, 
Travis (or similar continuous integration systems) need to first build `Rcpp`, which takes 
too much time, some of which being used to build components of `Rcpp` that are not relevant 
to the target package. Embedding the relevant subset of the codebase within the package
takes care of this. 

Legacy work
-----------

To some extent, project might be perceived as a follow up to the initial implementation effort in `Rcpp11` 
(François, Ushey and Chambers. 2014). This project is more ambitious than `Rcpp11` was, and it is more 
likely to be a success because now the tools area ready. 

Plan
====

The project can be conceptually divided into two parts. 

  - Design and implementation of the API classes
  - Framework to allow users to include relevant parts of the API into their packages. 
  
The two parts are linked, therefore the timeline below can only be a rough estimate. Each 
week of the timeline represents at most 3 days of work, so at most 24 hours. The amount of work
effectively dedicated to the project may vary depending on my workload in other projects. 

Week 1-3: Setup
---------------

  - Publish initial blog post 
  - Setup discussion channels, probably using a custom slack team
  - Contact potential interested parties. I have mentioned my intention to go forward with 
    this project at various conferences, and some people seemed interested to transition from `Rcpp`
    to a more modern implementation. 
  - Discuss important design decisions. 
    - The envisioned distribution (as separate components that are 
      embedded into client packages) requires design. We don't want users to have to manually 
      copy and paste files into their project, so we have to find the best way to move the header files 
      based on what components are used. The solution might involve an R package with functions performing 
      the relevant copies, or solutions at the git level such as git sub modules or git sub trees. 
    - Where in the source tree of the client package should the API headers be deployed. It is important
      that these files are isolated from the actual code of the client package. 
      
Week 4-6: API class review and design
-------------------------------------

  - The API aims to be conceptually compatible with `Rcpp`, i.e. each relevant R class gets a 
    dedicated C++ class, for example numeric vectors are handled by the `NumericVector` class. 
  - A review of the existing classes is needed to decide the interface. Some interface might be 
    kept, i.e. constructing a numeric vector by giving it the target size, but some behavior is
    likely to need to be updated. 
  - The deliverable from that step is a set of documents, of a format to be defined, detailing 
    the classes and their interface. 
    
Week 7: Skeleton implementation of a subset
-------------------------------------------

  - In order to test distribution of the API in the coming weeks, we need to have an 
    initial subset of the API implemented
    
Week 8-9: Formalizing distribution
----------------------------------

  - This step is critical to the success of the project. If we come up with good classes and
    interfaces but fail to find ways to use it easily, the project will likely not be a success. 
  - We will use the API subset implemented on week 5 to test embedding the code into a package, using 
    the mechanism agreed on earlier. 
  - This step might lead to reconsider the chosen mechanism. It might not work or be too complicated. 
    
Week 10-15: full API implementation
-----------------------------------

  - Implementation of the API classes designed previously
  - Iteratively test the embedding as new components are included
  
Week 16-18: Sugar
----------------

  - `Rcpp` sugar is a technology based on expression templates (Veldhuizen 1995) to have a syntax
    close to R syntax at the C++ level. 
  - Although it provides syntax comfort, sugar somewhat goes against one of the main message when 
    moving from R to C++ code, namely that writing loops is fine in C++ and should not 
    be associated with the same guilty conscience as when using loops in R code. Modern high level 
    languages such as Julia (Bezanson, Karpinski, Shah and Edelman 2012) even go as far as advocating 
    for de-vectorizing code and indeed write loops. 
  - We will need to decide whether sugar should be an integral part of the new API, or if we should 
    encourage external contributions to implement the feature as an external component. 
  - Whether we decide to include sugar or not, we need to lead the way and review the current techniques
    for modern expression templates. 
  - With the availability of lambda functions for C++, a minimal sugar implementation might just be
    constituted of implementations of C++ equivalents to `sapply` and `mapply` 
    
Week 17-22: Modules
-------------------

  - `Rcpp` modules enables use of C++ classes at the R level. It was largely inspired from 
    the `Boost.Python` (Abrahams 2003) library providing similar (although more complete) features for python. 
  - Modules were very hard to develop with the C++98 standard, therefore the code is bloated. 
  - We need to revise underlying technologies based on more modern C++ syntax, i.e. variadic templates are likely 
    to play a part. 
  - `RcppR6` (FitzJohn, 2015) has been developed as an alternative to modules. We need to review the solution, 
    identify what problems it solves that modules don't, encourage a discussion with its author. 

Week 23-24: Documentation
-------------------------

  - Documentation will be kept in mind as a background thread during the whole project, but this phase
    will be dedicated to it. 
  - Blog post, and potentially article in the R Journal or similar venue about the solution. 
  - Blog post detailing migration to the modernized version. 

Week 25-26: Stress Test
-----------------------

  - Dedicate time specifically for testing, this is in addition to the testing that will also be added 
    during all other phases. 

Week 27-30: Dissemination
-------------------------
  
  - Contact potential consumers of R/C++ API and encourage them to test the solution
  - Allow time to fix issues
  - Release to CRAN (if appropriate) or at least some venue that allows use by other packages. 

Failure mode and recovery
-------------------------

The elephant in the room is the existence of `Rcpp`. I absolutely don't see this 
initiative as a competition against `Rcpp`. I have great respect for the work 
that is done by the maintainers and I am still very proud of what `Rcpp`has become. 
The extreme care for stability is the absolute 
priority of `Rcpp` and that's great. This however limits innovation and redesign. I strongly 
believe that there is room for both and that the approach described here offers a better
compromise between stability and innovation. 

Success of the project will depend on the willingness of package authors to 
consider using the new API. To maximize probability of success, we must have good 
documentation highlighting key differences and advantages of the new API. 

The most important part, and the one we must absolutely get right, is the distribution of 
the code. It should be simple enough so that it does not get in the way. It should be easy 
to switch from one version of the API to another. Doing this right reduces the risk 
of packages using old version of the code base for wrong reasons. 

Because the API will be redesigned, we cannot guarantee compatibility with the existing `Rcpp` interface, 
transitioning from one implementation to the other will have to be based on documentation of
differences. Furthermore we cannot guarantee, at least in the project's infancy 
full compatibility between different versions. We aim to achieve flextability, i.e. a compromise
between flexibility and stability. However, with the embedding design, package authors are not forced to upgrade, 
they can keep the version of the API they've tested against. 

Help requested
==============

I would like to ask for financial support to cover part of the time needed for the design and implementation 
of this modernized R/C++ API, and cover costs for attending a major conference such as useR and/or some 
meetups to spread the word. 

Help in choosing the right licensing model for this project would also be very valuable. 

Budget Plan
===========

Thanks to other projects (e.g. `r-hub`) and available infrastructure, we do not envision 
hardware costs. The code will be developed on our machines and tested across `r-hub`, `travis`, ...

Documentation can be hosted as github pages. We might want to register a specific domain name 
for the blog and documentation, but the cost in negligible.  

What the project really needs is time, and therefore financial support to sponsor that time. The estimated timeline
above represents 3 days a week during 30 weeks. ThinkR will cover one day of work per week allocated to 
this project. I would like to ask the consortium for financial support for $48,000 to cover the remaining 480 hours
of development time. 

Acknowledgements
================

I would like to thank ThinkR for believing in the project, and allowing me to dedicate it some of my work time, 
and my colleagues Diane Beldame and Vincent Guyader for encouraging me to go forward with this proposal. 

I would like to thank Gabor Csardi, Jeroen Ooms and Kirill Müller for their constructive feedback on this proposal. 

Dissemination
=============

The `rstats-cpp` organization has been created on github to host various artifacts from this initiative. Code and 
documentation will be continuously uploaded to several repositories within this organization. 

The nature of the expected distribution of the code (i.e. embedding the API code inside the client package) 
requires careful selection of a licensing model. It has to be compatible with R package development
and values supported by the consortium. It seems that `Rcpp`'s choice of using the GPL license is too 
restrictive in some settings. 

In addition to blog posts on the consortium blog and article in a venue such as the R Journal for broad exposure, 
it makes sense to have a dedicated blog to document progress or highlight specific features being developed. We'll probably 
use hugo (https://gohugo.io) over github pages to host the blog. 

The project will ideally also need to be presented in major R conferences and meetups. 

About the author
===============

I have been trained as a statistician at the university in Montpellier, and ISUP in Paris. I have been 
professionally involved in the R community for more than 10 years, for Mango Solutions between 2006 and 2008, 
as a freelancer for 8 years, and as a Consulting Datactive for ThinkR since Feb 2017. We are not based 
in 221B Baker Street, however we are based in France, where every street is Baker Street. 

My interest for connecting R and C++ is not new. I have been involved in the development of the current
solution, originally inspired from the design of `rJava` (Urbanek 2016). Nowadays `Rcpp`'s maintainership 
is centered on backwards compatibility and stability, and I don't dispute the value of this choice from
the Rcpp Core Team. I however believe that there is room for (perhaps disruptive) innovation and redesign. 
As an author of `Rcpp` and one of its top historical contributors, I can leverage my experience and knowledge 
to design the next generation of an R/C++ bridge. 

Aside from my consulting and training responsibilities at ThinkR, I have a dedicated portion of my time 
devoted to the development of open source solutions. This project of modernization of the R/C++
interface is my top priority in that context. Support from the R Consortium will allow me to 
dedicate more time to the project, and/or hire extra hands. The nature and performance of the R language 
requires to leverage external compiled languages, C++ was and remains the best candidate and the 
R community deserves the very best design for a bridge between the two languages. 

References
==========

David Abrahams. 2003. Building Hybrid Systems with Boost.Python. http://www.boost.org/doc/libs/1_63_0/libs/python/doc/html/article.html

Jeff Bezanson, Stefan Karpinski, Viral B. Shah, Alan Edelman. 2012. Julia: A fast dynamic language for technical computing. https://arxiv.org/abs/1209.5145

Dirk Eddelbuettel, and Romain François. 2011. Rcpp: Seamless R and C++ Integration. *Journal of Statistical Software* 40 (8): 1–18. http://www.jstatsoft.org/v40/i08/.

Rich FitzJohn. 2015. Code-generation Wrapping C++ Classes as R6 Classes. 

Romain François, Kevin Ushey and John Chambers. 2014. Rcpp11: R and C++11. https://github.com/Rcpp11/Rcpp11

Duncan Murdoch, Uwe Ligges, Qiang Kou, Kevin Ushey, JJ Allaire, Avraham Adler and Jeroen Ooms. 2016.
Building R for Windows with the new gcc 4.9.3 toolchain. https://github.com/rwinlib/r-base#readme

Simon Urbanek. 2016. rJava: Low-Level R to Java Interface. R package version 0.9-8. https://CRAN.R-project.org/package=rJava

Todd Veldhuizen. 1995. Expression templates. C++ Report, Vol 7 No. 5. https://web.archive.org/web/20050210090012/http://osl.iu.edu/~tveldhui/papers/Expression-Templates/exprtmpl.html
